### ISSUE TITLE
Possible logic bug?

### ISSUE THREAD

**Issue by edgeman16** [luckytoilet/MSolver#1]
See screenshot:
http://i.imgur.com/MUaYz.jpg
The logic should not have guessed at the square it clicked on (red bomb), given that a 2 was next to it, with only 3 squares, and one-and-only-one of the other two squares known to be a bomb...

Any ideas?

**Comment by JacobAMason** [comment]
If bf7bc2f fixed this, can you mark this issue as closed? I'm using this code as a demo of backtracking and may contribute back if I find anything odd.

**Comment by lucky-bai** [comment]
Yup! Closing.
